E0205 11:35:02.846000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [408/0] failed while attempting to run meta for aten.pixel_shuffle.default
E0205 11:35:02.846000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [408/0] Traceback (most recent call last):
E0205 11:35:02.846000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [408/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_subclasses/fake_tensor.py", line 2376, in _dispatch_impl
E0205 11:35:02.846000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [408/0]     r = func(*args, **kwargs)
E0205 11:35:02.846000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [408/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_ops.py", line 749, in __call__
E0205 11:35:02.846000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [408/0]     return self._op(*args, **kwargs)
E0205 11:35:02.846000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [408/0]            ~~~~~~~~^^^^^^^^^^^^^^^^^
E0205 11:35:02.846000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [408/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_meta_registrations.py", line 6488, in meta_pixel_shuffle
E0205 11:35:02.846000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [408/0]     len(self.shape) > 2 and self.shape[-3] % (upscale_factor * upscale_factor) == 0
E0205 11:35:02.846000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [408/0] AssertionError: Invalid input shape for pixel_shuffle: torch.Size([1, 10, s0 + 2, s1 + 6, s2 + 6]) with upscale_factor = 2
