E0127 12:02:02.651000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [51/0] failed while attempting to run meta for aten.max_pool2d_with_indices.default
E0127 12:02:02.651000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [51/0] Traceback (most recent call last):
E0127 12:02:02.651000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [51/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_subclasses/fake_tensor.py", line 2376, in _dispatch_impl
E0127 12:02:02.651000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [51/0]     r = func(*args, **kwargs)
E0127 12:02:02.651000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [51/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_ops.py", line 749, in __call__
E0127 12:02:02.651000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [51/0]     return self._op(*args, **kwargs)
E0127 12:02:02.651000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [51/0]            ~~~~~~~~^^^^^^^^^^^^^^^^^
E0127 12:02:02.651000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [51/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_meta_registrations.py", line 4638, in meta_max_pool2d_with_indices
E0127 12:02:02.651000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [51/0]     ) = max_pool2d_checks_and_compute_shape(
E0127 12:02:02.651000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [51/0]         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
E0127 12:02:02.651000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [51/0]         input, kernel_size, stride, padding, dilation, ceil_mode
E0127 12:02:02.651000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [51/0]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0127 12:02:02.651000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [51/0]     )
E0127 12:02:02.651000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [51/0]     ^
E0127 12:02:02.651000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [51/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_meta_registrations.py", line 4547, in max_pool2d_checks_and_compute_shape
E0127 12:02:02.651000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [51/0]     torch._check(
E0127 12:02:02.651000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [51/0]     ~~~~~~~~~~~~^
E0127 12:02:02.651000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [51/0]         input.dim() in [3, 4],
E0127 12:02:02.651000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [51/0]         ^^^^^^^^^^^^^^^^^^^^^^
E0127 12:02:02.651000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [51/0]         lambda: "non-empty 3D or 4D (batch mode) tensor expected for input",
E0127 12:02:02.651000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [51/0]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0127 12:02:02.651000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [51/0]     )
E0127 12:02:02.651000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [51/0]     ^
E0127 12:02:02.651000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [51/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/__init__.py", line 1651, in _check
E0127 12:02:02.651000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [51/0]     _check_with(RuntimeError, cond, message)
E0127 12:02:02.651000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [51/0]     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0127 12:02:02.651000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [51/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/__init__.py", line 1633, in _check_with
E0127 12:02:02.651000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [51/0]     raise error_type(message_evaluated)
E0127 12:02:02.651000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [51/0] RuntimeError: non-empty 3D or 4D (batch mode) tensor expected for input
