E0205 14:27:46.981000 1612526 site-packages/torch/_subclasses/fake_tensor.py:2380] [65/0] failed while attempting to run meta for aten.pixel_shuffle.default
E0205 14:27:46.981000 1612526 site-packages/torch/_subclasses/fake_tensor.py:2380] [65/0] Traceback (most recent call last):
E0205 14:27:46.981000 1612526 site-packages/torch/_subclasses/fake_tensor.py:2380] [65/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_subclasses/fake_tensor.py", line 2376, in _dispatch_impl
E0205 14:27:46.981000 1612526 site-packages/torch/_subclasses/fake_tensor.py:2380] [65/0]     r = func(*args, **kwargs)
E0205 14:27:46.981000 1612526 site-packages/torch/_subclasses/fake_tensor.py:2380] [65/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_ops.py", line 749, in __call__
E0205 14:27:46.981000 1612526 site-packages/torch/_subclasses/fake_tensor.py:2380] [65/0]     return self._op(*args, **kwargs)
E0205 14:27:46.981000 1612526 site-packages/torch/_subclasses/fake_tensor.py:2380] [65/0]            ~~~~~~~~^^^^^^^^^^^^^^^^^
E0205 14:27:46.981000 1612526 site-packages/torch/_subclasses/fake_tensor.py:2380] [65/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_meta_registrations.py", line 6488, in meta_pixel_shuffle
E0205 14:27:46.981000 1612526 site-packages/torch/_subclasses/fake_tensor.py:2380] [65/0]     len(self.shape) > 2 and self.shape[-3] % (upscale_factor * upscale_factor) == 0
E0205 14:27:46.981000 1612526 site-packages/torch/_subclasses/fake_tensor.py:2380] [65/0] AssertionError: Invalid input shape for pixel_shuffle: torch.Size([1, 10, s0 + 4, s1 + 4]) with upscale_factor = 2
