E0205 10:42:58.618000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [166/0] failed while attempting to run meta for aten.glu.default
E0205 10:42:58.618000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [166/0] Traceback (most recent call last):
E0205 10:42:58.618000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [166/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_subclasses/fake_tensor.py", line 2376, in _dispatch_impl
E0205 10:42:58.618000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [166/0]     r = func(*args, **kwargs)
E0205 10:42:58.618000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [166/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_ops.py", line 749, in __call__
E0205 10:42:58.618000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [166/0]     return self._op(*args, **kwargs)
E0205 10:42:58.618000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [166/0]            ~~~~~~~~^^^^^^^^^^^^^^^^^
E0205 10:42:58.618000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [166/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_prims_common/wrappers.py", line 305, in _fn
E0205 10:42:58.618000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [166/0]     result = fn(*args, **kwargs)
E0205 10:42:58.618000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [166/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_prims_common/wrappers.py", line 146, in _fn
E0205 10:42:58.618000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [166/0]     result = fn(**bound.arguments)
E0205 10:42:58.618000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [166/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_refs/nn/functional/__init__.py", line 1186, in glu
E0205 10:42:58.618000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [166/0]     torch._check(
E0205 10:42:58.618000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [166/0]     ~~~~~~~~~~~~^
E0205 10:42:58.618000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [166/0]         a.shape[dim] % 2 == 0,
E0205 10:42:58.618000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [166/0]         ^^^^^^^^^^^^^^^^^^^^^^
E0205 10:42:58.618000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [166/0]         lambda: f"Halving dimension must be even, but dimension {dim} is size {a.shape[dim]}",
E0205 10:42:58.618000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [166/0]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0205 10:42:58.618000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [166/0]     )
E0205 10:42:58.618000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [166/0]     ^
E0205 10:42:58.618000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [166/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/__init__.py", line 1651, in _check
E0205 10:42:58.618000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [166/0]     _check_with(RuntimeError, cond, message)
E0205 10:42:58.618000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [166/0]     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0205 10:42:58.618000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [166/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/__init__.py", line 1633, in _check_with
E0205 10:42:58.618000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [166/0]     raise error_type(message_evaluated)
E0205 10:42:58.618000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [166/0] RuntimeError: Halving dimension must be even, but dimension 1 is size 1
