E0205 11:52:52.926000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [457/0] failed while attempting to run meta for aten.channel_shuffle.default
E0205 11:52:52.926000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [457/0] Traceback (most recent call last):
E0205 11:52:52.926000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [457/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_subclasses/fake_tensor.py", line 2376, in _dispatch_impl
E0205 11:52:52.926000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [457/0]     r = func(*args, **kwargs)
E0205 11:52:52.926000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [457/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_ops.py", line 749, in __call__
E0205 11:52:52.926000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [457/0]     return self._op(*args, **kwargs)
E0205 11:52:52.926000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [457/0]            ~~~~~~~~^^^^^^^^^^^^^^^^^
E0205 11:52:52.926000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [457/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_prims_common/wrappers.py", line 305, in _fn
E0205 11:52:52.926000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [457/0]     result = fn(*args, **kwargs)
E0205 11:52:52.926000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [457/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_refs/nn/functional/__init__.py", line 294, in channel_shuffle
E0205 11:52:52.926000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [457/0]     torch._check(
E0205 11:52:52.926000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [457/0]     ~~~~~~~~~~~~^
E0205 11:52:52.926000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [457/0]         (c % groups) == 0,
E0205 11:52:52.926000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [457/0]         ^^^^^^^^^^^^^^^^^^
E0205 11:52:52.926000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [457/0]         lambda: f"Number of channels must be divisible by groups. Got {c} channels and {groups} groups.",
E0205 11:52:52.926000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [457/0]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0205 11:52:52.926000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [457/0]     )
E0205 11:52:52.926000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [457/0]     ^
E0205 11:52:52.926000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [457/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/__init__.py", line 1651, in _check
E0205 11:52:52.926000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [457/0]     _check_with(RuntimeError, cond, message)
E0205 11:52:52.926000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [457/0]     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0205 11:52:52.926000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [457/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/__init__.py", line 1633, in _check_with
E0205 11:52:52.926000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [457/0]     raise error_type(message_evaluated)
E0205 11:52:52.926000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [457/0] RuntimeError: Number of channels must be divisible by groups. Got 3 channels and 4 groups.
