E0204 21:00:41.317000 2742634 site-packages/torch/_subclasses/fake_tensor.py:2380] [671/0] failed while attempting to run meta for aten.avg_pool2d.default
E0204 21:00:41.317000 2742634 site-packages/torch/_subclasses/fake_tensor.py:2380] [671/0] Traceback (most recent call last):
E0204 21:00:41.317000 2742634 site-packages/torch/_subclasses/fake_tensor.py:2380] [671/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_subclasses/fake_tensor.py", line 2376, in _dispatch_impl
E0204 21:00:41.317000 2742634 site-packages/torch/_subclasses/fake_tensor.py:2380] [671/0]     r = func(*args, **kwargs)
E0204 21:00:41.317000 2742634 site-packages/torch/_subclasses/fake_tensor.py:2380] [671/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_ops.py", line 749, in __call__
E0204 21:00:41.317000 2742634 site-packages/torch/_subclasses/fake_tensor.py:2380] [671/0]     return self._op(*args, **kwargs)
E0204 21:00:41.317000 2742634 site-packages/torch/_subclasses/fake_tensor.py:2380] [671/0]            ~~~~~~~~^^^^^^^^^^^^^^^^^
E0204 21:00:41.317000 2742634 site-packages/torch/_subclasses/fake_tensor.py:2380] [671/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_meta_registrations.py", line 2628, in meta_avg_pool2d
E0204 21:00:41.317000 2742634 site-packages/torch/_subclasses/fake_tensor.py:2380] [671/0]     pool2d_shape_check(
E0204 21:00:41.317000 2742634 site-packages/torch/_subclasses/fake_tensor.py:2380] [671/0]     ~~~~~~~~~~~~~~~~~~^
E0204 21:00:41.317000 2742634 site-packages/torch/_subclasses/fake_tensor.py:2380] [671/0]         input,
E0204 21:00:41.317000 2742634 site-packages/torch/_subclasses/fake_tensor.py:2380] [671/0]         ^^^^^^
E0204 21:00:41.317000 2742634 site-packages/torch/_subclasses/fake_tensor.py:2380] [671/0]     ...<13 lines>...
E0204 21:00:41.317000 2742634 site-packages/torch/_subclasses/fake_tensor.py:2380] [671/0]         memory_format,
E0204 21:00:41.317000 2742634 site-packages/torch/_subclasses/fake_tensor.py:2380] [671/0]         ^^^^^^^^^^^^^^
E0204 21:00:41.317000 2742634 site-packages/torch/_subclasses/fake_tensor.py:2380] [671/0]     )
E0204 21:00:41.317000 2742634 site-packages/torch/_subclasses/fake_tensor.py:2380] [671/0]     ^
E0204 21:00:41.317000 2742634 site-packages/torch/_subclasses/fake_tensor.py:2380] [671/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_meta_registrations.py", line 4288, in pool2d_shape_check
E0204 21:00:41.317000 2742634 site-packages/torch/_subclasses/fake_tensor.py:2380] [671/0]     torch._check(
E0204 21:00:41.317000 2742634 site-packages/torch/_subclasses/fake_tensor.py:2380] [671/0]     ~~~~~~~~~~~~^
E0204 21:00:41.317000 2742634 site-packages/torch/_subclasses/fake_tensor.py:2380] [671/0]         outputWidth >= 1 and outputHeight >= 1,
E0204 21:00:41.317000 2742634 site-packages/torch/_subclasses/fake_tensor.py:2380] [671/0]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0204 21:00:41.317000 2742634 site-packages/torch/_subclasses/fake_tensor.py:2380] [671/0]     ...<2 lines>...
E0204 21:00:41.317000 2742634 site-packages/torch/_subclasses/fake_tensor.py:2380] [671/0]         "Output size is too small",
E0204 21:00:41.317000 2742634 site-packages/torch/_subclasses/fake_tensor.py:2380] [671/0]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0204 21:00:41.317000 2742634 site-packages/torch/_subclasses/fake_tensor.py:2380] [671/0]     )
E0204 21:00:41.317000 2742634 site-packages/torch/_subclasses/fake_tensor.py:2380] [671/0]     ^
E0204 21:00:41.317000 2742634 site-packages/torch/_subclasses/fake_tensor.py:2380] [671/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/__init__.py", line 1651, in _check
E0204 21:00:41.317000 2742634 site-packages/torch/_subclasses/fake_tensor.py:2380] [671/0]     _check_with(RuntimeError, cond, message)
E0204 21:00:41.317000 2742634 site-packages/torch/_subclasses/fake_tensor.py:2380] [671/0]     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0204 21:00:41.317000 2742634 site-packages/torch/_subclasses/fake_tensor.py:2380] [671/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/__init__.py", line 1633, in _check_with
E0204 21:00:41.317000 2742634 site-packages/torch/_subclasses/fake_tensor.py:2380] [671/0]     raise error_type(message_evaluated)
E0204 21:00:41.317000 2742634 site-packages/torch/_subclasses/fake_tensor.py:2380] [671/0] RuntimeError: Given input size: (64x1x1). Calculated output size: (64x1x0). Output size is too small
