E0205 14:30:53.743000 1612526 site-packages/torch/_subclasses/fake_tensor.py:2380] [207/0] failed while attempting to run meta for aten.fractional_max_pool3d.default
E0205 14:30:53.743000 1612526 site-packages/torch/_subclasses/fake_tensor.py:2380] [207/0] Traceback (most recent call last):
E0205 14:30:53.743000 1612526 site-packages/torch/_subclasses/fake_tensor.py:2380] [207/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_subclasses/fake_tensor.py", line 2376, in _dispatch_impl
E0205 14:30:53.743000 1612526 site-packages/torch/_subclasses/fake_tensor.py:2380] [207/0]     r = func(*args, **kwargs)
E0205 14:30:53.743000 1612526 site-packages/torch/_subclasses/fake_tensor.py:2380] [207/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_ops.py", line 749, in __call__
E0205 14:30:53.743000 1612526 site-packages/torch/_subclasses/fake_tensor.py:2380] [207/0]     return self._op(*args, **kwargs)
E0205 14:30:53.743000 1612526 site-packages/torch/_subclasses/fake_tensor.py:2380] [207/0]            ~~~~~~~~^^^^^^^^^^^^^^^^^
E0205 14:30:53.743000 1612526 site-packages/torch/_subclasses/fake_tensor.py:2380] [207/0] RuntimeError: fractional_max_pool3d_out(): pool width 2 too large relative to input width 5
