E0204 20:42:29.896000 2742634 site-packages/torch/_subclasses/fake_tensor.py:2380] [5/0] failed while attempting to run meta for aten.pixel_shuffle.default
E0204 20:42:29.896000 2742634 site-packages/torch/_subclasses/fake_tensor.py:2380] [5/0] Traceback (most recent call last):
E0204 20:42:29.896000 2742634 site-packages/torch/_subclasses/fake_tensor.py:2380] [5/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_subclasses/fake_tensor.py", line 2376, in _dispatch_impl
E0204 20:42:29.896000 2742634 site-packages/torch/_subclasses/fake_tensor.py:2380] [5/0]     r = func(*args, **kwargs)
E0204 20:42:29.896000 2742634 site-packages/torch/_subclasses/fake_tensor.py:2380] [5/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_ops.py", line 749, in __call__
E0204 20:42:29.896000 2742634 site-packages/torch/_subclasses/fake_tensor.py:2380] [5/0]     return self._op(*args, **kwargs)
E0204 20:42:29.896000 2742634 site-packages/torch/_subclasses/fake_tensor.py:2380] [5/0]            ~~~~~~~~^^^^^^^^^^^^^^^^^
E0204 20:42:29.896000 2742634 site-packages/torch/_subclasses/fake_tensor.py:2380] [5/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_meta_registrations.py", line 6488, in meta_pixel_shuffle
E0204 20:42:29.896000 2742634 site-packages/torch/_subclasses/fake_tensor.py:2380] [5/0]     len(self.shape) > 2 and self.shape[-3] % (upscale_factor * upscale_factor) == 0
E0204 20:42:29.896000 2742634 site-packages/torch/_subclasses/fake_tensor.py:2380] [5/0] AssertionError: Invalid input shape for pixel_shuffle: torch.Size([1, 3, 32, 32]) with upscale_factor = 2
