E0127 11:36:06.611000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [410/0] failed while attempting to run meta for aten.max_pool3d_with_indices.default
E0127 11:36:06.611000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [410/0] Traceback (most recent call last):
E0127 11:36:06.611000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [410/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_subclasses/fake_tensor.py", line 2376, in _dispatch_impl
E0127 11:36:06.611000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [410/0]     r = func(*args, **kwargs)
E0127 11:36:06.611000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [410/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_ops.py", line 749, in __call__
E0127 11:36:06.611000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [410/0]     return self._op(*args, **kwargs)
E0127 11:36:06.611000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [410/0]            ~~~~~~~~^^^^^^^^^^^^^^^^^
E0127 11:36:06.611000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [410/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_decomp/__init__.py", line 123, in _fn
E0127 11:36:06.611000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [410/0]     return f(*args, **kwargs, out=None if is_none else out_kwargs)
E0127 11:36:06.611000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [410/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_prims_common/wrappers.py", line 305, in _fn
E0127 11:36:06.611000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [410/0]     result = fn(*args, **kwargs)
E0127 11:36:06.611000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [410/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_meta_registrations.py", line 4791, in meta_max_pool3d_with_indices
E0127 11:36:06.611000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [410/0]     torch._check(
E0127 11:36:06.611000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [410/0]     ~~~~~~~~~~~~^
E0127 11:36:06.611000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [410/0]         input.ndim in (4, 5),
E0127 11:36:06.611000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [410/0]         ^^^^^^^^^^^^^^^^^^^^^
E0127 11:36:06.611000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [410/0]         lambda: "non-empty 4D or 5D (batch mode) tensor expected for input",
E0127 11:36:06.611000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [410/0]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0127 11:36:06.611000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [410/0]     )
E0127 11:36:06.611000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [410/0]     ^
E0127 11:36:06.611000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [410/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/__init__.py", line 1651, in _check
E0127 11:36:06.611000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [410/0]     _check_with(RuntimeError, cond, message)
E0127 11:36:06.611000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [410/0]     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0127 11:36:06.611000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [410/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/__init__.py", line 1633, in _check_with
E0127 11:36:06.611000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [410/0]     raise error_type(message_evaluated)
E0127 11:36:06.611000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [410/0] RuntimeError: non-empty 4D or 5D (batch mode) tensor expected for input
