E0127 09:57:00.875000 3192161 site-packages/torch/_subclasses/fake_tensor.py:2380] [399/0] failed while attempting to run meta for aten.avg_pool2d.default
E0127 09:57:00.875000 3192161 site-packages/torch/_subclasses/fake_tensor.py:2380] [399/0] Traceback (most recent call last):
E0127 09:57:00.875000 3192161 site-packages/torch/_subclasses/fake_tensor.py:2380] [399/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_subclasses/fake_tensor.py", line 2376, in _dispatch_impl
E0127 09:57:00.875000 3192161 site-packages/torch/_subclasses/fake_tensor.py:2380] [399/0]     r = func(*args, **kwargs)
E0127 09:57:00.875000 3192161 site-packages/torch/_subclasses/fake_tensor.py:2380] [399/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_ops.py", line 749, in __call__
E0127 09:57:00.875000 3192161 site-packages/torch/_subclasses/fake_tensor.py:2380] [399/0]     return self._op(*args, **kwargs)
E0127 09:57:00.875000 3192161 site-packages/torch/_subclasses/fake_tensor.py:2380] [399/0]            ~~~~~~~~^^^^^^^^^^^^^^^^^
E0127 09:57:00.875000 3192161 site-packages/torch/_subclasses/fake_tensor.py:2380] [399/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_meta_registrations.py", line 2628, in meta_avg_pool2d
E0127 09:57:00.875000 3192161 site-packages/torch/_subclasses/fake_tensor.py:2380] [399/0]     pool2d_shape_check(
E0127 09:57:00.875000 3192161 site-packages/torch/_subclasses/fake_tensor.py:2380] [399/0]     ~~~~~~~~~~~~~~~~~~^
E0127 09:57:00.875000 3192161 site-packages/torch/_subclasses/fake_tensor.py:2380] [399/0]         input,
E0127 09:57:00.875000 3192161 site-packages/torch/_subclasses/fake_tensor.py:2380] [399/0]         ^^^^^^
E0127 09:57:00.875000 3192161 site-packages/torch/_subclasses/fake_tensor.py:2380] [399/0]     ...<13 lines>...
E0127 09:57:00.875000 3192161 site-packages/torch/_subclasses/fake_tensor.py:2380] [399/0]         memory_format,
E0127 09:57:00.875000 3192161 site-packages/torch/_subclasses/fake_tensor.py:2380] [399/0]         ^^^^^^^^^^^^^^
E0127 09:57:00.875000 3192161 site-packages/torch/_subclasses/fake_tensor.py:2380] [399/0]     )
E0127 09:57:00.875000 3192161 site-packages/torch/_subclasses/fake_tensor.py:2380] [399/0]     ^
E0127 09:57:00.875000 3192161 site-packages/torch/_subclasses/fake_tensor.py:2380] [399/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_meta_registrations.py", line 4288, in pool2d_shape_check
E0127 09:57:00.875000 3192161 site-packages/torch/_subclasses/fake_tensor.py:2380] [399/0]     torch._check(
E0127 09:57:00.875000 3192161 site-packages/torch/_subclasses/fake_tensor.py:2380] [399/0]     ~~~~~~~~~~~~^
E0127 09:57:00.875000 3192161 site-packages/torch/_subclasses/fake_tensor.py:2380] [399/0]         outputWidth >= 1 and outputHeight >= 1,
E0127 09:57:00.875000 3192161 site-packages/torch/_subclasses/fake_tensor.py:2380] [399/0]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0127 09:57:00.875000 3192161 site-packages/torch/_subclasses/fake_tensor.py:2380] [399/0]     ...<2 lines>...
E0127 09:57:00.875000 3192161 site-packages/torch/_subclasses/fake_tensor.py:2380] [399/0]         "Output size is too small",
E0127 09:57:00.875000 3192161 site-packages/torch/_subclasses/fake_tensor.py:2380] [399/0]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0127 09:57:00.875000 3192161 site-packages/torch/_subclasses/fake_tensor.py:2380] [399/0]     )
E0127 09:57:00.875000 3192161 site-packages/torch/_subclasses/fake_tensor.py:2380] [399/0]     ^
E0127 09:57:00.875000 3192161 site-packages/torch/_subclasses/fake_tensor.py:2380] [399/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/__init__.py", line 1651, in _check
E0127 09:57:00.875000 3192161 site-packages/torch/_subclasses/fake_tensor.py:2380] [399/0]     _check_with(RuntimeError, cond, message)
E0127 09:57:00.875000 3192161 site-packages/torch/_subclasses/fake_tensor.py:2380] [399/0]     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0127 09:57:00.875000 3192161 site-packages/torch/_subclasses/fake_tensor.py:2380] [399/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/__init__.py", line 1633, in _check_with
E0127 09:57:00.875000 3192161 site-packages/torch/_subclasses/fake_tensor.py:2380] [399/0]     raise error_type(message_evaluated)
E0127 09:57:00.875000 3192161 site-packages/torch/_subclasses/fake_tensor.py:2380] [399/0] RuntimeError: Given input size: (10xs0*s1 - 4x1). Calculated output size: (10x(((s0*s1)//2)) - 2x0). Output size is too small
